- hosts: all
  vars_files:
  - "{{ ansible_facts['distribution'] }}.yml"

  tasks:
  - name: Installing Package...
    package:
      name: "{{ package_name }}"
      state: present

  - name: Copying The webpage../
    template:
      dest: "{{ doc_root }}/my.html"
      src: my.html.j2

  - name: Starting WEB SERVICE..
    service:
      name: "{{ service_name }}"
      state: started
